#!/usr/bin/env python3
"""
Pentest Report Generator

Reads structured findings (JSON) and generates a formatted markdown report
with all required sections including security enhancement recommendations.

Usage:
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md>
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md> --upload-drive --gdrive-account hatlesswhite@gmail.com
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md> --create-slides --slides-title "Pentest Report"

Findings JSON format:
{
    "target": "192.168.1.105",
    "findings": [...],
    "enhancements": [...]
}
"""

import json
import argparse
import subprocess
import sys
import shutil
import tempfile
import os
import re
from pathlib import Path
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
except ImportError:
    Document = None
    Inches = Pt = WD_PARAGRAPH_ALIGNMENT = None


SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

try:
    from pentest_pptx_generator import PentestPPTXGenerator
except Exception:
    PentestPPTXGenerator = None

from cvss_v4 import CVSS_V4_VERSION_LABEL, coerce_legacy_cvss_v4

DOC_TEMPLATE = ROOT / "assets" / "docs" / "ncompass-reference.docx"
LOGO_PATH = ROOT / "assets" / "branding" / "ncompass-logo.png"


def _coerce_nonempty_string(value):
    if value is None:
        return None
    text = str(value).strip()
    return text or None


def _first_present(mapping, *keys):
    for key in keys:
        if key in mapping:
            value = mapping.get(key)
            if value is not None:
                return value
    return None


def normalize_finding_cvss(finding):
    if not isinstance(finding, dict):
        return finding

    normalized = coerce_legacy_cvss_v4(finding)

    for key in ("cvss", "cvss_version", "cvss_vector", "cvss_rationale", "cvss_note", "cvss_label", "cvss_severity", "cvss_assumptions"):
        value = normalized.get(key)
        if isinstance(value, str):
            normalized[key] = value.strip()

    return normalized


def normalize_report_data(data):
    if not isinstance(data, dict):
        return data
    normalized = dict(data)
    normalized["findings"] = [normalize_finding_cvss(f) for f in data.get("findings", [])]
    return normalized


def export_doc_to_pdf(doc_id, account=None, output=None):
    if output is None:
        fd, path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)
        output = Path(path)
    else:
        output = Path(output)
    cmd = ["gog", "docs", "export", doc_id, "--format", "pdf", "--out", str(output)]
    if account:
        cmd.extend(["-a", account])
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"gog docs export failed: {result.stderr.strip()}")
    return output


def build_docx(data, output_path):
    if Document is None:
        raise RuntimeError("python-docx is required to generate branded DOCX files")
    doc = Document()
    section = doc.sections[0]
    header = section.header
    for paragraph in header.paragraphs:
        paragraph.clear()
    header_image = ROOT / "assets" / "docs" / "header-banner.png"
    if header_image.exists():
        run = header.paragraphs[0].add_run()
        run.add_picture(str(header_image), width=Inches(4.5))
        header.paragraphs[0].alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_heading(f"Penetration Test Report — {data.get('target', 'Unknown')}", level=1)
    doc.add_paragraph(f"Date: {datetime.now().strftime('%e %B %Y')}".strip())
    doc.add_paragraph(f"Generated by: specter-report")

    doc.add_heading("1. Executive Summary", level=2)
    findings = data.get('findings', [])
    top_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get('severity', 'Info'), 99))[:3]
    qs = data.get('quick_scan_sections', {}) or {}
    summary_paras = clean_bullets(qs.get('executive_summary'))
    if not summary_paras:
        summary_paras = [
            f"{len(findings)} findings across the {data.get('target', 'target')} scope.",
            "Top findings:",
        ]
        for f in top_findings:
            summary_paras.append(f"- {f.get('id')} — {f.get('title')} ({f.get('severity')})")
    for line in summary_paras:
        if line.startswith('- '):
            paragraph = doc.add_paragraph(line[2:], style='List Bullet')
        else:
            doc.add_paragraph(line)

    section_no = 2
    for title, key in [("Target Fingerprint", 'target_fingerprint'), ("Why This Quick Scan Varied", 'why_varied')]:
        extra_lines = clean_bullets(qs.get(key))
        if extra_lines:
            doc.add_heading(f"{section_no}. {title}", level=2)
            for line in extra_lines:
                doc.add_paragraph(line, style='List Bullet')
            section_no += 1

    doc.add_heading(f"{section_no}. Methodology", level=2)
    if data.get('quick_scan'):
        doc.add_paragraph("Quick-scan phases executed: Recon → Enumeration → Vulnerability Analysis. This is a rapid, low-impact triage workflow rather than a full pentest.")
    else:
        doc.add_paragraph("Structured phases executed: Recon → Enumeration → Vulnerability Analysis → Exploitation → Post-Exploitation → Reporting.")

    section_no += 1
    doc.add_heading(f"{section_no}. Findings", level=2)
    for f in findings:
        doc.add_heading(f"{f.get('id', 'Finding')} — {f.get('title', '')}", level=3)
        doc.add_paragraph(f"Severity: {f.get('severity')}  |  CVSS: {f.get('cvss', 'N/A')}" )
        if f.get('cvss_version'):
            doc.add_paragraph(f"CVSS Version: {f.get('cvss_version')}")
        if f.get('cvss_vector'):
            doc.add_paragraph(f"CVSS Vector: {f.get('cvss_vector')}")
        if f.get('cvss_rationale'):
            doc.add_paragraph(f"CVSS Rationale: {f.get('cvss_rationale')}")
        if f.get('priority'):
            doc.add_paragraph(f"Priority: {f.get('priority')}")
        fcvss_note = f.get('cvss_note')
        if fcvss_note:
            doc.add_paragraph(f"Scoring Note: {fcvss_note}")
        doc.add_paragraph(f"Affected: {f.get('affected', 'N/A')}")
        doc.add_paragraph(f"Description: {f.get('description', '')}")
        if f.get('technical_basis'):
            doc.add_paragraph(f"Technical Basis: {f.get('technical_basis', '')}")
        doc.add_paragraph(f"Evidence: {f.get('evidence', '')}")
        if f.get('reproduction'):
            doc.add_paragraph(f"Reproduction / Validation Steps: {f.get('reproduction', '')}")
        doc.add_paragraph(f"Impact: {f.get('impact', '')}")
        doc.add_paragraph(f"Remediation: {f.get('remediation', '')}")
        if f.get('retest_guidance'):
            doc.add_paragraph(f"Retest Guidance: {f.get('retest_guidance', '')}")
        doc.add_paragraph(f"Hardening: {f.get('hardening', '')}")
        if f.get('cleanup_notes'):
            doc.add_paragraph(f"Cleanup / Side-Effect Notes: {f.get('cleanup_notes', '')}")
        refs = f.get('references')
        if refs:
            doc.add_paragraph("References: " + ", ".join(refs))

    section_no += 1
    doc.add_heading(f"{section_no}. Security Enhancements", level=2)
    enhancements = list(data.get('enhancements', []))
    for line in clean_bullets(qs.get('quick_recommendations')):
        enhancements.append({"category": "Quick Scan", "recommendation": line})
    for enh in enhancements:
        doc.add_paragraph(f"{enh.get('category')}: {enh.get('recommendation')}", style='List Bullet')

    next_actions = clean_bullets(qs.get('recommended_next_action'))
    if next_actions:
        section_no += 1
        doc.add_heading(f"{section_no}. Recommended Next Action", level=2)
        for line in next_actions:
            doc.add_paragraph(line, style='List Bullet')

    doc.save(output_path)
    return output_path


def run_gog(command):
    """Run a gog command and return parsed JSON when possible."""
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "gog command failed")

    stdout = result.stdout.strip()
    if not stdout:
        return None

    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        return stdout


def upload_to_drive(path, account=None, parent=None, convert_to=None):
    """Upload a file to Google Drive via gog."""
    cmd = ["gog", "drive", "upload", path, "--json"]
    if account:
        cmd.extend(["-a", account])
    if parent:
        cmd.extend(["--parent", parent])
    if convert_to:
        cmd.extend(["--convert-to", convert_to])
    return run_gog(cmd)


def upload_pptx_as_slides(path, account=None, parent=None, name=None):
    """Upload a PPTX and convert it to Google Slides via gog."""
    cmd = ["gog", "drive", "upload", path, "--json", "--convert-to", "slides"]
    if account:
        cmd.extend(["-a", account])
    if parent:
        cmd.extend(["--parent", parent])
    if name:
        cmd.extend(["--name", name])
    return run_gog(cmd)


def severity_counts(findings):
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
    for f in findings:
        sev = f.get("severity", "Info")
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def clean_bullets(lines):
    cleaned = []
    for line in lines or []:
        text = str(line).strip()
        if not text:
            continue
        if text.startswith("- "):
            text = text[2:].strip()
        cleaned.append(text)
    return cleaned


def smart_truncate(text, limit=120):
    text = " ".join(str(text or "").split())
    if len(text) <= limit:
        return text
    cut = text[:limit].rstrip()
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut


def clean_text(text):
    return " ".join(str(text or "").split()).strip(" .;:")


def extract_complete_sentence(text):
    text = clean_text(text)
    if not text:
        return ""
    parts = re.split(r"(?<=[.!?])\s+", text)
    if parts and parts[0].strip():
        return parts[0].strip().rstrip(" .;:")
    return text


def extract_summary_lead(text):
    raw = str(text or "").strip()
    if not raw:
        return ""
    first_line = raw.splitlines()[0].strip()
    if first_line:
        return first_line.rstrip(" :;.-")
    cleaned = clean_text(raw)
    cleaned = re.split(r"\b1\.\s+", cleaned, maxsplit=1)[0].strip()
    return cleaned.rstrip(" :;.-")


def concise_phrase(text, limit=56):
    text = clean_text(text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rstrip()
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut.strip(" .;:")


def summarize_exposure(affected):
    affected = clean_text(affected)
    if not affected:
        return "Exposure not specified"
    return concise_phrase(affected, 48)


def summarize_fix(text):
    lead = extract_summary_lead(text)
    sentence = extract_complete_sentence(text)
    text = clean_text(text)
    lower = text.lower()
    lead_lower = lead.lower()
    sentence_lower = sentence.lower()
    if lead:
        direct_patterns = [
            "enforce smb signing via group policy",
            "restrict mysql network exposure",
            "configure rdp to reduce information disclosure via group policy",
        ]
        for pattern in direct_patterns:
            if pattern in lead_lower:
                return lead
    patterns = [
        ("missing security control", "Apply the missing security header or control and verify it in a follow-up scan"),
        ("verify the header/control is present", "Apply the missing security header or control and verify it in a follow-up scan"),
        ("validate the observation manually", "Validate the exposure manually and harden the service if it is unnecessary"),
        ("restrict access", "Restrict access to trusted admin hosts"),
        ("host firewall", "Restrict exposure with host firewall rules"),
        ("network segmentation", "Segment administrative services from the user LAN"),
        ("disable", "Disable the service if it is not required"),
        ("vpn", "Require VPN or jump-host access"),
        ("mfa", "Require MFA for remote administration"),
        ("monitor", "Monitor remote access activity"),
        ("patch", "Keep the service fully patched"),
    ]
    for needle, summary in patterns:
        if needle in lower or needle in sentence_lower:
            return summary
    if sentence and len(sentence.split()) <= 14:
        return sentence
    if lead and len(lead.split()) <= 12:
        return lead
    return "Remediate the issue and confirm the fix in a follow-up validation scan"


def summarize_hardening(text):
    lead = extract_summary_lead(text)
    sentence = extract_complete_sentence(text)
    text = clean_text(text)
    lower = text.lower()
    lead_lower = lead.lower()
    if lead:
        direct_patterns = [
            "additional hardening recommendations",
            "database hardening recommendations",
            "additional smb hardening",
        ]
        for pattern in direct_patterns:
            if pattern in lead_lower:
                break
        else:
            if len(lead.split()) <= 10:
                return lead
    patterns = [
        ("admin", "Limit access to admin systems only"),
        ("monitor", "Alert on suspicious access patterns"),
        ("segment", "Keep management ports off the user LAN"),
        ("mfa", "Protect admin access with MFA"),
        ("vpn", "Use VPN or a bastion for remote access"),
        ("signing", "Enforce secure protocol settings"),
        ("patch", "Maintain a regular patching schedule"),
        ("database", "Harden database access and monitoring"),
        ("rdp", "Restrict and monitor remote desktop access"),
        ("expected network exposure", "Document expected exposure and alert on deviations"),
        ("exposed services minimized", "Minimize exposed services and monitor for unexpected access"),
    ]
    for needle, summary in patterns:
        if needle in lower:
            return summary
    if sentence and len(sentence.split()) <= 14:
        return sentence
    if lead and len(lead.split()) <= 12:
        return lead
    return "Reduce unnecessary exposure and monitor for unexpected access"


def summarize_title(title, limit=42):
    title = clean_text(title)
    replacements = {
        "SMB Signing Not Required": "SMB signing is optional",
        "Multiple Remote Administration Services Exposed": "Remote admin surface is broad",
        "RDP Reveals Domain and Host Metadata": "RDP leaks host metadata",
        "No Confirmed Legacy SMB Vulnerabilities in Safe NSE Pass": "No legacy SMB flaw confirmed",
    }
    return replacements.get(title, concise_phrase(title, limit))


def _split_paragraph_groups(value):
    cleaned = clean_text(value)
    if not cleaned:
        return []
    return [part.strip() for part in re.split(r"\n\s*\n+", cleaned) if part.strip()]


def finding_slide_summary(finding, quick_scan=False):
    if quick_scan:
        return [
            f"Risk: {summarize_title(finding.get('title', 'Untitled'))}",
            f"Exposure: {summarize_exposure(finding.get('affected', 'Not specified'))}",
            f"Fix: {summarize_fix(finding.get('remediation', 'No remediation provided'))}",
            f"Harden: {summarize_hardening(finding.get('hardening', 'No hardening guidance'))}",
        ]

    severity = str(finding.get('severity', 'Info')).upper()
    cvss = finding.get('cvss', 'N/A')
    status = finding.get('status', 'reported')
    lines = [
        f"Severity: {severity} | CVSS: {cvss} | Status: {status}",
        f"Affected: {clean_text(finding.get('affected', 'Not specified')) or 'Not specified'}",
    ]
    if finding.get('cvss_version'):
        lines.append(f"CVSS Version: {clean_text(finding.get('cvss_version'))}")
    if finding.get('cvss_vector'):
        lines.append(f"Vector: {clean_text(finding.get('cvss_vector'))}")
    if finding.get('cvss_rationale'):
        lines.append(f"Rationale: {clean_text(finding.get('cvss_rationale'))}")
    if finding.get('priority'):
        lines.append(f"Priority: {clean_text(finding.get('priority'))}")

    detail_fields = [
        ("Description", finding.get('description', '')),
        ("Impact", finding.get('impact', '')),
        ("Remediation", finding.get('remediation', '')),
        ("Hardening", finding.get('hardening', '')),
    ]
    for label, value in detail_fields:
        groups = _split_paragraph_groups(value)
        if not groups:
            continue
        lines.append(f"{label}:")
        for group in groups:
            lines.append(f"• {group}")
    return lines


def chunked(items, size):
    if size <= 0:
        return [list(items)]
    return [items[i:i + size] for i in range(0, len(items), size)]


def build_styled_pptx(data, output_path, title=None):
    """Create a styled PPTX deck from report data."""
    if PentestPPTXGenerator is None:
        raise RuntimeError("python-pptx generator unavailable")

    target = data.get("target", "Unknown Target")
    findings = sorted(data.get("findings", []), key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    enhancements = data.get("enhancements", [])
    counts = severity_counts(findings)
    overall = next((sev for sev in ["Critical", "High", "Medium", "Low", "Info"] if counts.get(sev, 0) > 0), "Info")
    qs = data.get("quick_scan_sections", {}) or {}
    exec_bullets = clean_bullets(qs.get("executive_summary"))
    fingerprint_bullets = clean_bullets(qs.get("target_fingerprint"))
    why_varied = clean_bullets(qs.get("why_varied"))
    next_actions = clean_bullets(qs.get("recommended_next_action"))
    deck_title = title or f"Pentest Report — {target}"
    date_str = datetime.now().strftime("%B %d, %Y")

    logo_path = ROOT / "assets" / "branding" / "ncompass-logo.png"
    gen = PentestPPTXGenerator(theme="ncompass", logo_path=str(logo_path) if logo_path.exists() else None)
    gen.add_title_slide(deck_title, "Security Assessment Results", date_str, overall)

    if exec_bullets:
        exec_lines = [f"• {line}" for line in exec_bullets[:8]]
    elif data.get("quick_scan"):
        exec_lines = [
            f"Target: {concise_phrase(target, 42)}",
            f"Findings: {len(findings)} issues identified",
            f"Highest risk: {overall.upper()}",
            "",
        ]
        for f in findings[:5]:
            exec_lines.append(f"• {f.get('id', 'V-???')}: {summarize_title(f.get('title', 'Untitled'))}")
    else:
        exec_lines = [
            f"Target: {clean_text(target) or 'Unknown Target'}",
            f"Findings: {len(findings)} issues identified",
            f"Highest risk: {overall.upper()}",
            "",
        ]
        for f in findings[:5]:
            title_text = clean_text(f.get('title', 'Untitled')) or 'Untitled'
            severity = str(f.get('severity', 'Info')).upper()
            exec_lines.append(f"• {f.get('id', 'V-???')} ({severity}): {title_text}")
    gen.add_content_slide("Executive Summary", exec_lines)

    scope_lines = [
        "Assessment type: quick scan triage workflow" if data.get("quick_scan") else "Assessment type: structured penetration test",
        "Rules of engagement: safe or low-impact checks only" if data.get("quick_scan") else "Rules of engagement: activities performed within the authorized engagement scope",
        "Limitation: findings require manual validation before being treated as confirmed vulnerabilities" if data.get("quick_scan") else "Limitation: findings were documented from the assessed evidence set and should be revalidated during remediation and retest",
        "Method: Recon, Enumeration, Analysis, Reporting" if data.get("quick_scan") else "Method: Reconnaissance, Enumeration, Vulnerability Analysis, Exploitation assessment, Post-Exploitation review, and Reporting",
    ]
    gen.add_content_slide("Scope, ROE, and Methodology", scope_lines)

    if fingerprint_bullets:
        gen.add_content_slide("Target Fingerprint", [f"• {line}" for line in fingerprint_bullets[:8]])

    if why_varied or next_actions:
        story_lines = [f"• {line}" for line in (why_varied[:4] + next_actions[:3])]
        gen.add_content_slide("Attack Path / Engagement Story", story_lines[:8])

    left = [
        f"Critical: {counts['Critical']}",
        f"High: {counts['High']}",
        f"Medium: {counts['Medium']}",
        f"Low: {counts['Low']}",
        f"Info: {counts['Info']}",
    ]
    right = [
        "Quick target fingerprint completed",
        "Safe enumeration completed",
        "Triage findings and context prepared",
        "Published report and remediation prepared",
    ]
    gen.add_two_column_slide("Risk Overview", "Severity Counts", left, "Assessment Scope", right)

    overview_chunks = chunked(findings, 6)
    for idx, finding_chunk in enumerate(overview_chunks, start=1):
        rows = []
        for f in finding_chunk:
            rows.append([
                f.get("id", "V-???"),
                f.get("severity", "Info").upper(),
                str(f.get("cvss", "-")),
                summarize_title(f.get("title", "Untitled")),
            ])
        if rows:
            title_text = "Findings Summary" if idx == 1 else f"Findings Summary ({idx}/{len(overview_chunks)})"
            gen.add_table_slide(title_text, ["ID", "Severity", "CVSS", "Finding"], rows)

    for f in findings:
        is_quick_scan = bool(data.get('quick_scan'))
        content = finding_slide_summary(f, quick_scan=is_quick_scan)
        title_limit = 42 if is_quick_scan else 72
        gen.add_content_slide(
            f"{f.get('id', 'V-???')} — {summarize_title(f.get('title', 'Untitled'), limit=title_limit)}",
            content,
        )

    immediate = []
    short_term = []
    for f in findings:
        sev = f.get("severity", "Info")
        item = f"{f.get('id', 'V-???')}: {summarize_fix(f.get('remediation', 'No remediation'))}"
        if sev in ("Critical", "High"):
            immediate.append(item)
        else:
            short_term.append(item)
    if enhancements:
        for enh in enhancements:
            short_term.append(f"{enh.get('category', 'General')}: {summarize_hardening(enh.get('recommendation', ''))}")

    immediate_chunks = chunked(immediate, 5) or [["No immediate actions recorded"]]
    short_term_chunks = chunked(short_term, 5) or [["No planned actions recorded"]]
    roadmap_pages = max(len(immediate_chunks), len(short_term_chunks))
    for idx in range(roadmap_pages):
        left_items = immediate_chunks[idx] if idx < len(immediate_chunks) else ["No additional immediate actions"]
        right_items = short_term_chunks[idx] if idx < len(short_term_chunks) else ["No additional planned actions"]
        title_text = "Remediation and Retest Roadmap" if idx == 0 else f"Remediation and Retest Roadmap ({idx + 1}/{roadmap_pages})"
        gen.add_two_column_slide(
            title_text,
            "Immediate Priority",
            left_items,
            "Planned Hardening",
            right_items,
        )

    cleanup_lines = [
        "Cleanup: no target-side cleanup actions were captured by this reporting workflow",
        "Residual risk: triage candidates may still indicate real exposure until manually validated and remediated",
    ]
    if next_actions:
        cleanup_lines.extend([f"Next: {line}" for line in next_actions[:4]])
    gen.add_content_slide("Cleanup, Residual Risk, and Next Steps", cleanup_lines[:8])

    gen.save(output_path)
    return output_path


def generate_executive_summary(findings, enhancements):
    """Generate plain-language executive summary."""
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
    for f in findings:
        sev = f.get("severity", "Info")
        counts[sev] = counts.get(sev, 0) + 1

    total = len(findings)
    lines = []
    lines.append(f"This assessment identified **{total} findings** across the target:\n")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    for sev in ["Critical", "High", "Medium", "Low", "Info"]:
        if counts[sev] > 0:
            lines.append(f"| {sev} | {counts[sev]} |")

    # Top 3 findings
    sorted_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    if sorted_findings:
        lines.append(f"\n### Priority Actions\n")
        for i, f in enumerate(sorted_findings[:3], 1):
            impact_summary = smart_truncate(f.get('impact', 'No impact description'), 140)
            lines.append(f"{i}. **{f.get('title', 'Untitled')}** ({f.get('severity', 'N/A')}) — {impact_summary}")

    return "\n".join(lines)


def parse_bullet_fields(text):
    parsed = {}
    current_key = None
    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("## "):
            current_key = None
            continue
        if stripped.startswith("- **") and ":**" in stripped:
            try:
                key_part, value = stripped[4:].split(":**", 1)
            except ValueError:
                continue
            current_key = key_part.strip().lower()
            parsed[current_key] = value.strip()
        elif stripped.startswith("- ") and current_key:
            extra = stripped[2:].strip()
            if extra and not extra.startswith("**"):
                parsed[current_key] = (parsed.get(current_key, "") + " " + extra).strip()
    return parsed


def load_preengagement_context(target):
    slug = (target or "").strip()
    if not slug:
        return {}

    candidates = []
    direct_pre = ROOT / "engagements" / slug / "pre-engagement"
    direct_legacy = ROOT / "engagements" / slug / "00-charter"
    candidates.extend([direct_pre, direct_legacy])

    lowered = slug.lower()
    if lowered != slug:
        candidates.append(ROOT / "engagements" / lowered / "pre-engagement")
        candidates.append(ROOT / "engagements" / lowered / "00-charter")

    normalized = "".join(ch.lower() for ch in slug if ch.isalnum())
    engagements_root = ROOT / "engagements"
    if engagements_root.exists():
        for child in engagements_root.iterdir():
            if not child.is_dir():
                continue
            child_norm = "".join(ch.lower() for ch in child.name if ch.isalnum())
            if child_norm == normalized:
                candidates.append(child / "pre-engagement")
                candidates.append(child / "00-charter")

    seen = set()
    context = {}
    for base in candidates:
        key = str(base)
        if key in seen:
            continue
        seen.add(key)
        charter_path = base / "engagement-charter.md"
        roe_path = base / "scope-and-roe.md"
        if charter_path.exists():
            context["charter_path"] = str(charter_path.relative_to(ROOT))
            context["charter"] = parse_bullet_fields(charter_path.read_text())
        if roe_path.exists():
            context["roe_path"] = str(roe_path.relative_to(ROOT))
            context["roe"] = parse_bullet_fields(roe_path.read_text())
        if context.get("charter") or context.get("roe"):
            break
    return context


def append_preengagement_section(lines, section_no, context):
    charter = context.get("charter") or {}
    roe = context.get("roe") or {}
    if not charter and not roe:
        return section_no

    lines.append(f"## {section_no}. Pre-Engagement Intake")
    lines.append("")
    lines.append("### Engagement Charter")
    lines.append("")
    charter_fields = [
        ("engagement title", "Engagement title"),
        ("target", "Target"),
        ("test type", "Test type"),
        ("start date", "Start date"),
        ("end date", "End date"),
        ("status", "Status"),
        ("approval / authorization reference", "Approval / authorization reference"),
        ("success criteria", "Success criteria"),
        ("primary analyst", "Primary analyst"),
    ]
    for key, label in charter_fields:
        value = charter.get(key)
        if value:
            lines.append(f"- **{label}:** {value}")
    if charter.get("constraints"):
        lines.append(f"- **Constraints:** {charter['constraints']}")
    if charter.get("credentials provided"):
        lines.append(f"- **Credentials provided:** {charter['credentials provided']}")
    lines.append("")
    lines.append("### Scope and Rules of Engagement")
    lines.append("")
    roe_fields = [
        ("testing window", "Testing window"),
        ("allowed techniques", "Allowed techniques"),
        ("prohibited techniques", "Prohibited techniques"),
        ("dos allowed?", "DoS allowed?"),
        ("persistence allowed?", "Persistence allowed?"),
        ("social engineering allowed?", "Social engineering allowed?"),
        ("third-party / cloud approvals", "Third-party / cloud approvals"),
        ("authorization confirmed?", "Authorization confirmed?"),
        ("provider approvals confirmed?", "Provider approvals confirmed?"),
        ("cleared for active testing?", "Cleared for active testing?"),
    ]
    for key, label in roe_fields:
        value = roe.get(key)
        if value:
            lines.append(f"- **{label}:** {value}")
    if roe.get("scope in"):
        lines.append(f"- **Scope in:** {roe['scope in']}")
    if roe.get("scope out"):
        lines.append(f"- **Scope out:** {roe['scope out']}")
    if roe.get("fragile systems / constraints"):
        lines.append(f"- **Fragile systems / constraints:** {roe['fragile systems / constraints']}")
    if roe.get("collection limits"):
        lines.append(f"- **Collection limits:** {roe['collection limits']}")
    if roe.get("storage expectations"):
        lines.append(f"- **Storage expectations:** {roe['storage expectations']}")
    if roe.get("retention / destruction"):
        lines.append(f"- **Retention / destruction:** {roe['retention / destruction']}")
    if roe.get("sensitive data handling"):
        lines.append(f"- **Sensitive data handling:** {roe['sensitive data handling']}")
    lines.append("")
    source_bits = []
    if context.get("charter_path"):
        source_bits.append(f"charter: `{context['charter_path']}`")
    if context.get("roe_path"):
        source_bits.append(f"scope/ROE: `{context['roe_path']}`")
    if source_bits:
        lines.append(f"- **Source documents:** {'; '.join(source_bits)}")
        lines.append("")
    lines.append("---")
    lines.append("")
    return section_no + 1


def format_finding(finding, index):
    """Format a single finding section."""
    lines = []
    fid = finding.get("id", f"VULN-{index:03d}")
    title = finding.get("title", "Untitled Finding")
    lines.append(f"### {fid} — {title}\n")
    lines.append(f"- **Severity:** {finding.get('severity', 'N/A')}")
    if finding.get("cvss"):
        lines.append(f"- **CVSS Score:** {finding['cvss']}")
    if finding.get("cvss_version"):
        lines.append(f"- **CVSS Version:** {finding['cvss_version']}")
    if finding.get("cvss_vector"):
        lines.append(f"- **CVSS Vector:** `{finding['cvss_vector']}`")
    if finding.get("cvss_rationale"):
        lines.append(f"- **CVSS Rationale:** {finding['cvss_rationale']}")
    if finding.get("cvss_note"):
        lines.append(f"- **Scoring Note:** {finding['cvss_note']}")
    if finding.get("priority"):
        lines.append(f"- **Priority:** {finding['priority']}")
    lines.append(f"- **Affected Target:** {finding.get('affected', 'N/A')}")
    lines.append(f"- **Description:** {finding.get('description', 'No description provided')}")
    lines.append(f"- **Evidence:** ```\n{finding.get('evidence', 'No evidence recorded')}\n```")
    lines.append(f"- **Impact:** {finding.get('impact', 'No impact assessment')}")
    lines.append(f"- **Remediation:** {finding.get('remediation', 'No remediation provided')}")

    if finding.get("hardening"):
        lines.append(f"- **Hardening:** {finding['hardening']}")

    if finding.get("references"):
        refs = finding["references"]
        if isinstance(refs, list):
            refs_str = ", ".join(refs)
        else:
            refs_str = str(refs)
        lines.append(f"- **References:** {refs_str}")

    return "\n".join(lines) + "\n"


def generate_report(data):
    """Generate the full report markdown."""
    target = data.get("target", "Unknown Target")
    findings = data.get("findings", [])
    enhancements = data.get("enhancements", [])
    date = datetime.now().strftime("%Y-%m-%d")
    counts = severity_counts(findings)
    sorted_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    overall_risk = next((sev for sev in ["Critical", "High", "Medium", "Low", "Info"] if counts.get(sev, 0) > 0), "Info")
    preengagement = load_preengagement_context(target) if not data.get("quick_scan") else {}

    lines = []

    lines.append(f"# Penetration Test Report — {target}")
    lines.append("")
    lines.append(f"**Status:** Final")
    lines.append(f"**Date:** {date}")
    lines.append(f"**Target:** {target}")
    lines.append(f"**Overall Risk:** {overall_risk}")
    lines.append(f"**Findings:** {len(findings)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    qs = data.get("quick_scan_sections", {}) or {}
    exec_lines = clean_bullets(qs.get("executive_summary"))
    target_fp_lines = clean_bullets(qs.get("target_fingerprint"))
    why_varied_lines = clean_bullets(qs.get("why_varied"))
    next_action_lines = clean_bullets(qs.get("recommended_next_action"))
    quick_reco_lines = clean_bullets(qs.get("quick_recommendations"))

    lines.append("## 1. Executive Summary")
    lines.append("")
    if exec_lines:
        for line in exec_lines:
            lines.append(f"- {line}")
    else:
        lines.append(generate_executive_summary(findings, enhancements))
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## 2. Scope, ROE, and Methodology")
    lines.append("")
    if data.get("quick_scan"):
        lines.append("- Assessment type: quick scan triage workflow")
        lines.append("- Intended use: rapid, low-impact exposure assessment and reporting triage")
        lines.append("- Rules of engagement: safe or low-impact checks only unless a selected profile explicitly broadens coverage")
        lines.append("- Limitation: this is not a full pentest and findings require manual validation before being treated as confirmed vulnerabilities")
        lines.append("")
        lines.append("**Phases executed**")
        lines.append("- Reconnaissance, lightweight target and exposure fingerprinting")
        lines.append("- Enumeration, safe surface validation and basic discovery")
        lines.append("- Vulnerability analysis, candidate weakness review from collected artifacts")
        lines.append("- Reporting, triage-oriented findings with next-step guidance")
    else:
        lines.append("- Assessment type: structured penetration test")
        lines.append("- Methodology: Reconnaissance, Enumeration, Vulnerability Analysis, Exploitation, Post-Exploitation, Reporting")
    lines.append("")
    lines.append("---")
    lines.append("")

    section_no = 3
    section_no = append_preengagement_section(lines, section_no, preengagement)
    if target_fp_lines:
        lines.append(f"## {section_no}. Target Fingerprint")
        lines.append("")
        for line in target_fp_lines:
            lines.append(f"- {line}")
        lines.append("")
        lines.append("---")
        lines.append("")
        section_no += 1

    if why_varied_lines:
        lines.append(f"## {section_no}. Why This Quick Scan Varied")
        lines.append("")
        for line in why_varied_lines:
            lines.append(f"- {line}")
        lines.append("")
        lines.append("---")
        lines.append("")
        section_no += 1

    lines.append(f"## {section_no}. Findings Summary")
    lines.append("")
    lines.append("| ID | Finding | Severity | Asset |")
    lines.append("|----|---------|----------|-------|")
    for i, f in enumerate(sorted_findings, 1):
        fid = f.get("id", f"VULN-{i:03d}")
        title = f.get("title", "Untitled")
        sev = f.get("severity", "N/A")
        asset = f.get("affected", target)
        lines.append(f"| {fid} | {title} | {sev} | {asset} |")
    if not sorted_findings:
        lines.append(f"| N/A | No confirmed findings packaged | Info | {target} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Attack Path / Engagement Story")
    lines.append("")
    if why_varied_lines or next_action_lines:
        story_lines = why_varied_lines[:3] + next_action_lines[:2]
        for line in story_lines:
            lines.append(f"- {line}")
    elif sorted_findings:
        top = sorted_findings[0]
        lines.append(f"- Primary engagement story: {top.get('title', 'Top finding')} was the strongest triage signal during this assessment.")
        lines.append(f"- Strongest observed impact: {top.get('impact', 'Impact requires validation.')}")
        lines.append("- This path remains a triage hypothesis until validated through deeper manual testing.")
    else:
        lines.append("- No attack path was established from the current quick-scan evidence set.")
    lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Detailed Findings")
    lines.append("")
    for i, finding in enumerate(sorted_findings, 1):
        lines.append(format_finding(finding, i))
    if not sorted_findings:
        lines.append("No detailed findings were packaged from the current data set.\n")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Remediation Roadmap")
    lines.append("")
    immediate = []
    short_term = []
    medium_term = []
    for f in sorted_findings:
        item = f"{f.get('id', 'V-???')} — {summarize_fix(f.get('remediation', 'No remediation provided'))}"
        sev = f.get("severity", "Info")
        if sev in ("Critical", "High"):
            immediate.append(item)
        elif sev == "Medium":
            short_term.append(item)
        else:
            medium_term.append(item)
    lines.append("**Immediate**")
    for item in immediate[:10] or ["No immediate remediation items captured"]:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("**Short-term**")
    for item in short_term[:10] or ["No short-term remediation items captured"]:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("**Medium-term hardening**")
    for item in medium_term[:10] or ["No medium-term hardening items captured"]:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Security Enhancement Recommendations")
    lines.append("")
    enhancement_items = list(enhancements)
    for line in quick_reco_lines:
        enhancement_items.append({"category": "Quick Scan Context", "recommendation": line})
    if enhancement_items:
        for enh in enhancement_items:
            cat = enh.get("category", "General")
            rec = enh.get("recommendation", "No recommendation provided")
            lines.append(f"### {cat}")
            lines.append("")
            lines.append(rec)
            lines.append("")
    else:
        lines.append("No additional enhancement recommendations identified.")
        lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Cleanup / Restoration Status")
    lines.append("")
    lines.append("- Tester-created artifacts introduced: none captured by this reporting workflow")
    lines.append("- Cleanup performed: not applicable for markdown report generation artifacts")
    lines.append("- Remaining changes on target: unknown from quick-scan triage alone, validate during deeper follow-up if needed")
    lines.append("- Residual risk: candidate findings may still indicate meaningful exposure until manually validated and remediated")
    lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Retest Guidance / Recommended Next Action")
    lines.append("")
    if next_action_lines:
        for line in next_action_lines:
            lines.append(f"- {line}")
    else:
        lines.append("- Re-test after remediation by rerunning the same profile and manually validating whether the previously observed exposure still reproduces.")
    lines.append("")
    lines.append("---")
    lines.append("")
    section_no += 1

    lines.append(f"## {section_no}. Appendices")
    lines.append("")
    lines.append("### A. Risk Summary Matrix")
    lines.append("")
    lines.append("| ID | Finding | Severity | Remediation Priority |")
    lines.append("|----|---------|----------|---------------------|")
    for i, f in enumerate(sorted_findings, 1):
        fid = f.get("id", f"VULN-{i:03d}")
        title = f.get("title", "Untitled")
        sev = f.get("severity", "N/A")
        priority = "Immediate" if sev in ("Critical", "High") else "Scheduled" if sev == "Medium" else "Low Priority"
        lines.append(f"| {fid} | {title} | {sev} | {priority} |")
    if not sorted_findings:
        lines.append("| N/A | No confirmed findings packaged | Info | Low Priority |")
    lines.append("")
    lines.append("### B. Tools Used")
    lines.append("")
    lines.append("- nmap, masscan (enumeration)")
    lines.append("- Metasploit, custom scripts (exploitation)")
    lines.append("- Shodan, crt.sh (OSINT)")
    lines.append("- Burp Suite, curl (web testing)")
    lines.append("")
    lines.append("### C. Scope Boundaries")
    lines.append("")
    lines.append("All testing was conducted within the authorized scope. No denial-of-service attacks were performed without explicit permission.")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate pentest report from findings JSON")
    parser.add_argument("--target", required=True, help="Target name/IP for report header")
    parser.add_argument("--findings", required=True, help="Path to findings JSON file")
    parser.add_argument("--output", required=True, help="Output report path (markdown)")
    parser.add_argument("--upload-drive", action="store_true", help="Upload generated report to Google Drive via gog")
    parser.add_argument("--create-doc", action="store_true", help="Create a native Google Doc from the generated markdown")
    parser.add_argument("--export-pdf", dest="export_pdf", action="store_true", default=True,
                        help="Export the generated Google Doc to PDF for preview (default: on)")
    parser.add_argument("--no-export-pdf", dest="export_pdf", action="store_false",
                        help="Do not export a PDF preview")
    parser.add_argument("--gdrive-account", help="Google account email for gog operations")
    parser.add_argument("--gdrive-parent", help="Optional parent Drive folder ID")
    parser.add_argument("--create-slides", action="store_true", help="Create a Google Slides deck from the generated markdown")
    parser.add_argument("--slides-title", help="Slides title (default: Penetration Test Report — <target>)")
    args = parser.parse_args()

    with open(args.findings) as f:
        data = normalize_report_data(json.load(f))

    report = generate_report(data)

    with open(args.output, "w") as f:
        f.write(report)

    print(f"[OK] Report generated: {args.output}")
    print(f"     Target: {args.target}")
    print(f"     Findings: {len(data.get('findings', []))}")
    print(f"     Enhancements: {len(data.get('enhancements', []))}")

    publish_summary = {
        "local_file": args.output,
        "drive_link": None,
        "doc_link": None,
        "slides_link": None,
        "pdf_link": None,
        "drive_id": None,
        "doc_id": None,
        "slides_id": None,
        "pdf_id": None,
    }
    summary_path = str(Path(args.output).with_suffix('.publish.json'))

    if args.upload_drive:
        try:
            upload_result = upload_to_drive(args.output, account=args.gdrive_account, parent=args.gdrive_parent)
            file_data = upload_result.get("file", upload_result) if isinstance(upload_result, dict) else upload_result
            if isinstance(file_data, dict):
                publish_summary["drive_id"] = file_data.get("id")
                publish_summary["drive_link"] = file_data.get("webViewLink")
                print(f"[OK] Drive upload: {file_data.get('name', args.output)}")
                if file_data.get("id"):
                    print(f"     Drive File ID: {file_data['id']}")
                if file_data.get("webViewLink"):
                    print(f"     Drive Link: {file_data['webViewLink']}")
            else:
                print(f"[OK] Drive upload completed: {file_data}")
        except Exception as e:
            print(f"[WARN] Drive upload failed: {e}")

    if args.create_doc:
        try:
            docx_path = Path(args.output).with_suffix(".docx")
            build_docx(data, str(docx_path))
            print(f"[OK] DocX generated: {docx_path}")
            doc_result = upload_to_drive(str(docx_path), account=args.gdrive_account, parent=args.gdrive_parent, convert_to="doc")
            doc_data = doc_result.get("file", doc_result) if isinstance(doc_result, dict) else doc_result
            if isinstance(doc_data, dict):
                publish_summary["doc_id"] = doc_data.get("id")
                publish_summary["doc_link"] = doc_data.get("webViewLink")
                print(f"[OK] Google Doc created: {doc_data.get('name', args.output)}")
                if doc_data.get("id"):
                    print(f"     Doc ID: {doc_data['id']}")
                if doc_data.get("webViewLink"):
                    print(f"     Doc Link: {doc_data['webViewLink']}")
            else:
                print(f"[OK] Google Doc created: {doc_data}")
        except Exception as e:
            print(f"[WARN] Google Doc creation failed: {e}")

    if args.create_doc and args.export_pdf and publish_summary.get("doc_id"):
        try:
            pdf_path = export_doc_to_pdf(publish_summary["doc_id"], account=args.gdrive_account)
            pdf_result = upload_to_drive(str(pdf_path), account=args.gdrive_account, parent=args.gdrive_parent)
            pdf_data = pdf_result.get("file", pdf_result) if isinstance(pdf_result, dict) else pdf_result
            if isinstance(pdf_data, dict):
                publish_summary["pdf_id"] = pdf_data.get("id")
                publish_summary["pdf_link"] = pdf_data.get("webViewLink")
                print(f"[OK] PDF preview uploaded: {pdf_data.get('name', pdf_path)}")
                if pdf_data.get("webViewLink"):
                    print(f"     PDF Link: {pdf_data['webViewLink']}")
            else:
                print(f"[OK] PDF preview uploaded: {pdf_data}")
            if pdf_path.exists():
                pdf_path.unlink()
        except Exception as e:
            print(f"[WARN] PDF export/upload failed: {e}")

    if args.create_slides:
        slides_title = args.slides_title or f"Penetration Test Report — {args.target}"
        try:
            pptx_output = str(Path(args.output).with_suffix(".pptx"))
            build_styled_pptx(data, pptx_output, title=slides_title)
            print(f"[OK] Styled PPTX generated: {pptx_output}")
            slides_result = upload_pptx_as_slides(pptx_output, account=args.gdrive_account, parent=args.gdrive_parent, name=slides_title)
            pres = slides_result.get("file", slides_result) if isinstance(slides_result, dict) else slides_result
            if isinstance(pres, dict):
                publish_summary["slides_id"] = pres.get("presentationId") or pres.get("id")
                publish_summary["slides_link"] = pres.get("webViewLink")
                if not publish_summary["slides_link"] and publish_summary["slides_id"]:
                    publish_summary["slides_link"] = f"https://docs.google.com/presentation/d/{publish_summary['slides_id']}/edit?usp=drivesdk"
                print(f"[OK] Styled Slides created: {pres.get('name', slides_title)}")
                if publish_summary["slides_id"]:
                    print(f"     Slides ID: {publish_summary['slides_id']}")
                if publish_summary["slides_link"]:
                    print(f"     Slides Link: {publish_summary['slides_link']}")
            else:
                print(f"[OK] Styled Slides created: {slides_result}")
        except Exception as e:
            print(f"[WARN] Slides creation failed: {e}")

    with open(summary_path, 'w') as f:
        json.dump(publish_summary, f, indent=2)
    print(f"[OK] Publish summary saved: {summary_path}")

    if any(publish_summary[k] for k in ("drive_link", "doc_link", "slides_link")):
        print("\n=== PUBLISHED LINKS ===")
        print(f"Local file: {publish_summary['local_file']}")
        if publish_summary["doc_link"]:
            print(f"Docs: {publish_summary['doc_link']}")
        if publish_summary["pdf_link"]:
            print(f"PDF preview: {publish_summary['pdf_link']}")
        if publish_summary["slides_link"]:
            print(f"Slides: {publish_summary['slides_link']}")
        if publish_summary["drive_link"]:
            print(f"Drive file: {publish_summary['drive_link']}")


if __name__ == "__main__":
    main()
