#!/usr/bin/env python3
"""
Pentest Report Generator

Reads structured findings (JSON) and generates a formatted markdown report
with all required sections including security enhancement recommendations.

Usage:
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md>
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md> --upload-drive --gdrive-account hatlesswhite@gmail.com
    python3 generate_report.py --target <target> --findings <findings.json> --output <report.md> --create-slides --slides-title "Pentest Report"

Findings JSON format:
{
    "target": "192.168.1.105",
    "findings": [...],
    "enhancements": [...]
}
"""

import json
import argparse
import subprocess
import sys
import shutil
import tempfile
import os
import re
from pathlib import Path
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
except ImportError:
    Document = None
    Inches = Pt = WD_PARAGRAPH_ALIGNMENT = None


SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Info": 4}

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

try:
    from pentest_pptx_generator import PentestPPTXGenerator
except Exception:
    PentestPPTXGenerator = None

DOC_TEMPLATE = ROOT / "assets" / "docs" / "ncompass-reference.docx"
LOGO_PATH = ROOT / "assets" / "branding" / "ncompass-logo.png"


def export_doc_to_pdf(doc_id, account=None, output=None):
    if output is None:
        fd, path = tempfile.mkstemp(suffix=".pdf")
        os.close(fd)
        output = Path(path)
    else:
        output = Path(output)
    cmd = ["gog", "docs", "export", doc_id, "--format", "pdf", "--out", str(output)]
    if account:
        cmd.extend(["-a", account])
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"gog docs export failed: {result.stderr.strip()}")
    return output


def build_docx(data, output_path):
    if Document is None:
        raise RuntimeError("python-docx is required to generate branded DOCX files")
    doc = Document()
    section = doc.sections[0]
    header = section.header
    for paragraph in header.paragraphs:
        paragraph.clear()
    header_image = ROOT / "assets" / "docs" / "header-banner.png"
    if header_image.exists():
        run = header.paragraphs[0].add_run()
        run.add_picture(str(header_image), width=Inches(4.5))
        header.paragraphs[0].alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    doc.add_heading(f"Penetration Test Report — {data.get('target', 'Unknown')}", level=1)
    doc.add_paragraph(f"Date: {datetime.now().strftime('%e %B %Y')}".strip())
    doc.add_paragraph(f"Generated by: specter-report")

    doc.add_heading("1. Executive Summary", level=2)
    findings = data.get('findings', [])
    top_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get('severity', 'Info'), 99))[:3]
    qs = data.get('quick_scan_sections', {}) or {}
    summary_paras = clean_bullets(qs.get('executive_summary'))
    if not summary_paras:
        summary_paras = [
            f"{len(findings)} findings across the {data.get('target', 'target')} scope.",
            "Top findings:",
        ]
        for f in top_findings:
            summary_paras.append(f"- {f.get('id')} — {f.get('title')} ({f.get('severity')})")
    for line in summary_paras:
        if line.startswith('- '):
            paragraph = doc.add_paragraph(line[2:], style='List Bullet')
        else:
            doc.add_paragraph(line)

    section_no = 2
    for title, key in [("Target Fingerprint", 'target_fingerprint'), ("Why This Quick Scan Varied", 'why_varied')]:
        extra_lines = clean_bullets(qs.get(key))
        if extra_lines:
            doc.add_heading(f"{section_no}. {title}", level=2)
            for line in extra_lines:
                doc.add_paragraph(line, style='List Bullet')
            section_no += 1

    doc.add_heading(f"{section_no}. Methodology", level=2)
    if data.get('quick_scan'):
        doc.add_paragraph("Quick-scan phases executed: Recon → Enumeration → Vulnerability Analysis. This is a rapid, low-impact triage workflow rather than a full pentest.")
    else:
        doc.add_paragraph("Structured phases executed: Recon → Enumeration → Vulnerability Analysis → Exploitation → Post-Exploitation → Reporting.")

    section_no += 1
    doc.add_heading(f"{section_no}. Findings", level=2)
    for f in findings:
        doc.add_heading(f"{f.get('id', 'Finding')} — {f.get('title', '')}", level=3)
        doc.add_paragraph(f"Severity: {f.get('severity')}  |  CVSS: {f.get('cvss', 'N/A')}" )
        doc.add_paragraph(f"Affected: {f.get('affected', 'N/A')}")
        doc.add_paragraph(f"Description: {f.get('description', '')}")
        doc.add_paragraph(f"Evidence: {f.get('evidence', '')}")
        doc.add_paragraph(f"Impact: {f.get('impact', '')}")
        doc.add_paragraph(f"Remediation: {f.get('remediation', '')}")
        doc.add_paragraph(f"Hardening: {f.get('hardening', '')}")
        refs = f.get('references')
        if refs:
            doc.add_paragraph("References: " + ", ".join(refs))

    section_no += 1
    doc.add_heading(f"{section_no}. Security Enhancements", level=2)
    enhancements = list(data.get('enhancements', []))
    for line in clean_bullets(qs.get('quick_recommendations')):
        enhancements.append({"category": "Quick Scan", "recommendation": line})
    for enh in enhancements:
        doc.add_paragraph(f"{enh.get('category')}: {enh.get('recommendation')}", style='List Bullet')

    next_actions = clean_bullets(qs.get('recommended_next_action'))
    if next_actions:
        section_no += 1
        doc.add_heading(f"{section_no}. Recommended Next Action", level=2)
        for line in next_actions:
            doc.add_paragraph(line, style='List Bullet')

    doc.save(output_path)
    return output_path


def run_gog(command):
    """Run a gog command and return parsed JSON when possible."""
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "gog command failed")

    stdout = result.stdout.strip()
    if not stdout:
        return None

    try:
        return json.loads(stdout)
    except json.JSONDecodeError:
        return stdout


def upload_to_drive(path, account=None, parent=None, convert_to=None):
    """Upload a file to Google Drive via gog."""
    cmd = ["gog", "drive", "upload", path, "--json"]
    if account:
        cmd.extend(["-a", account])
    if parent:
        cmd.extend(["--parent", parent])
    if convert_to:
        cmd.extend(["--convert-to", convert_to])
    return run_gog(cmd)


def upload_pptx_as_slides(path, account=None, parent=None, name=None):
    """Upload a PPTX and convert it to Google Slides via gog."""
    cmd = ["gog", "drive", "upload", path, "--json", "--convert-to", "slides"]
    if account:
        cmd.extend(["-a", account])
    if parent:
        cmd.extend(["--parent", parent])
    if name:
        cmd.extend(["--name", name])
    return run_gog(cmd)


def severity_counts(findings):
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
    for f in findings:
        sev = f.get("severity", "Info")
        counts[sev] = counts.get(sev, 0) + 1
    return counts


def clean_bullets(lines):
    cleaned = []
    for line in lines or []:
        text = str(line).strip()
        if not text:
            continue
        if text.startswith("- "):
            text = text[2:].strip()
        cleaned.append(text)
    return cleaned


def smart_truncate(text, limit=120):
    text = " ".join(str(text or "").split())
    if len(text) <= limit:
        return text
    cut = text[:limit].rstrip()
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut


def clean_text(text):
    return " ".join(str(text or "").split()).strip(" .;:")


def extract_complete_sentence(text):
    text = clean_text(text)
    if not text:
        return ""
    parts = re.split(r"(?<=[.!?])\s+", text)
    if parts and parts[0].strip():
        return parts[0].strip().rstrip(" .;:")
    return text


def extract_summary_lead(text):
    raw = str(text or "").strip()
    if not raw:
        return ""
    first_line = raw.splitlines()[0].strip()
    if first_line:
        return first_line.rstrip(" :;.-")
    cleaned = clean_text(raw)
    cleaned = re.split(r"\b1\.\s+", cleaned, maxsplit=1)[0].strip()
    return cleaned.rstrip(" :;.-")


def concise_phrase(text, limit=56):
    text = clean_text(text)
    if len(text) <= limit:
        return text
    cut = text[:limit].rstrip()
    if " " in cut:
        cut = cut.rsplit(" ", 1)[0]
    return cut.strip(" .;:")


def summarize_exposure(affected):
    affected = clean_text(affected)
    if not affected:
        return "Exposure not specified"
    return concise_phrase(affected, 48)


def summarize_fix(text):
    lead = extract_summary_lead(text)
    sentence = extract_complete_sentence(text)
    text = clean_text(text)
    lower = text.lower()
    lead_lower = lead.lower()
    sentence_lower = sentence.lower()
    if lead:
        direct_patterns = [
            "enforce smb signing via group policy",
            "restrict mysql network exposure",
            "configure rdp to reduce information disclosure via group policy",
        ]
        for pattern in direct_patterns:
            if pattern in lead_lower:
                return lead
    patterns = [
        ("missing security control", "Apply the missing security header or control and verify it in a follow-up scan"),
        ("verify the header/control is present", "Apply the missing security header or control and verify it in a follow-up scan"),
        ("validate the observation manually", "Validate the exposure manually and harden the service if it is unnecessary"),
        ("restrict access", "Restrict access to trusted admin hosts"),
        ("host firewall", "Restrict exposure with host firewall rules"),
        ("network segmentation", "Segment administrative services from the user LAN"),
        ("disable", "Disable the service if it is not required"),
        ("vpn", "Require VPN or jump-host access"),
        ("mfa", "Require MFA for remote administration"),
        ("monitor", "Monitor remote access activity"),
        ("patch", "Keep the service fully patched"),
    ]
    for needle, summary in patterns:
        if needle in lower or needle in sentence_lower:
            return summary
    if sentence and len(sentence.split()) <= 14:
        return sentence
    if lead and len(lead.split()) <= 12:
        return lead
    return "Remediate the issue and confirm the fix in a follow-up validation scan"


def summarize_hardening(text):
    lead = extract_summary_lead(text)
    sentence = extract_complete_sentence(text)
    text = clean_text(text)
    lower = text.lower()
    lead_lower = lead.lower()
    if lead:
        direct_patterns = [
            "additional hardening recommendations",
            "database hardening recommendations",
            "additional smb hardening",
        ]
        for pattern in direct_patterns:
            if pattern in lead_lower:
                break
        else:
            if len(lead.split()) <= 10:
                return lead
    patterns = [
        ("admin", "Limit access to admin systems only"),
        ("monitor", "Alert on suspicious access patterns"),
        ("segment", "Keep management ports off the user LAN"),
        ("mfa", "Protect admin access with MFA"),
        ("vpn", "Use VPN or a bastion for remote access"),
        ("signing", "Enforce secure protocol settings"),
        ("patch", "Maintain a regular patching schedule"),
        ("database", "Harden database access and monitoring"),
        ("rdp", "Restrict and monitor remote desktop access"),
        ("expected network exposure", "Document expected exposure and alert on deviations"),
        ("exposed services minimized", "Minimize exposed services and monitor for unexpected access"),
    ]
    for needle, summary in patterns:
        if needle in lower:
            return summary
    if sentence and len(sentence.split()) <= 14:
        return sentence
    if lead and len(lead.split()) <= 12:
        return lead
    return "Reduce unnecessary exposure and monitor for unexpected access"


def summarize_title(title):
    title = clean_text(title)
    replacements = {
        "SMB Signing Not Required": "SMB signing is optional",
        "Multiple Remote Administration Services Exposed": "Remote admin surface is broad",
        "RDP Reveals Domain and Host Metadata": "RDP leaks host metadata",
        "No Confirmed Legacy SMB Vulnerabilities in Safe NSE Pass": "No legacy SMB flaw confirmed",
    }
    return replacements.get(title, concise_phrase(title, 42))


def finding_slide_summary(finding):
    return [
        f"Risk: {summarize_title(finding.get('title', 'Untitled'))}",
        f"Exposure: {summarize_exposure(finding.get('affected', 'Not specified'))}",
        f"Fix: {summarize_fix(finding.get('remediation', 'No remediation provided'))}",
        f"Harden: {summarize_hardening(finding.get('hardening', 'No hardening guidance'))}",
    ]


def build_styled_pptx(data, output_path, title=None):
    """Create a styled PPTX deck from report data."""
    if PentestPPTXGenerator is None:
        raise RuntimeError("python-pptx generator unavailable")

    target = data.get("target", "Unknown Target")
    findings = sorted(data.get("findings", []), key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    enhancements = data.get("enhancements", [])
    counts = severity_counts(findings)
    overall = next((sev for sev in ["Critical", "High", "Medium", "Low", "Info"] if counts.get(sev, 0) > 0), "Info")
    qs = data.get("quick_scan_sections", {}) or {}
    exec_bullets = clean_bullets(qs.get("executive_summary"))
    fingerprint_bullets = clean_bullets(qs.get("target_fingerprint"))
    deck_title = title or f"Pentest Report — {target}"
    date_str = datetime.now().strftime("%B %d, %Y")

    logo_path = ROOT / "assets" / "branding" / "ncompass-logo.png"
    gen = PentestPPTXGenerator(theme="ncompass", logo_path=str(logo_path) if logo_path.exists() else None)
    gen.add_title_slide(deck_title, "Security Assessment Results", date_str, overall)

    top_findings = findings[:3]
    if exec_bullets:
        exec_lines = [f"• {line}" for line in exec_bullets[:6]]
    else:
        exec_lines = [
            f"Target: {concise_phrase(target, 42)}",
            f"Findings: {len(findings)} issues identified",
            f"Highest risk: {overall.upper()}",
            "",
        ]
        for f in top_findings:
            exec_lines.append(f"• {f.get('id', 'V-???')}: {summarize_title(f.get('title', 'Untitled'))}")
        if enhancements:
            exec_lines.extend(["", f"• {len(enhancements)} hardening themes included"])
    gen.add_content_slide("Executive Summary", exec_lines)

    if fingerprint_bullets:
        gen.add_content_slide("Target Fingerprint", [f"• {line}" for line in fingerprint_bullets[:6]])

    left = [
        f"Critical: {counts['Critical']}",
        f"High: {counts['High']}",
        f"Medium: {counts['Medium']}",
        f"Low: {counts['Low']}",
        f"Info: {counts['Info']}",
    ]
    right = [
        "Quick target fingerprint completed",
        "Safe enumeration completed",
        "Triage findings and context prepared",
        "Published report and remediation prepared",
    ]
    gen.add_two_column_slide("Risk Overview", "Severity Counts", left, "Assessment Scope", right)

    rows = []
    for f in findings[:6]:
        rows.append([
            f.get("id", "V-???"),
            f.get("severity", "Info").upper(),
            str(f.get("cvss", "-")),
            summarize_title(f.get("title", "Untitled")),
        ])
    if rows:
        gen.add_table_slide("Top Findings", ["ID", "Severity", "CVSS", "Finding"], rows)

    for f in top_findings:
        content = [
            f"{f.get('severity', 'Info').upper()} — CVSS {f.get('cvss', 'N/A')}",
            "",
            *finding_slide_summary(f),
        ]
        gen.add_content_slide(f"{f.get('id', 'V-???')} — {summarize_title(f.get('title', 'Untitled'))}", content)

    immediate = []
    short_term = []
    for f in findings:
        sev = f.get("severity", "Info")
        item = f"{f.get('id', 'V-???')}: {summarize_fix(f.get('remediation', 'No remediation'))}"
        if sev in ("Critical", "High") and len(immediate) < 4:
            immediate.append(item)
        elif sev in ("Medium", "Low", "Info") and len(short_term) < 4:
            short_term.append(item)
    if enhancements:
        for enh in enhancements[:2]:
            short_term.append(f"{enh.get('category', 'General')}: {summarize_hardening(enh.get('recommendation', ''))}")
    gen.add_two_column_slide(
        "Remediation Roadmap",
        "Immediate Priority",
        immediate or ["No immediate actions recorded"],
        "Planned Hardening",
        short_term or ["No planned actions recorded"],
    )

    gen.save(output_path)
    return output_path


def generate_executive_summary(findings, enhancements):
    """Generate plain-language executive summary."""
    counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
    for f in findings:
        sev = f.get("severity", "Info")
        counts[sev] = counts.get(sev, 0) + 1

    total = len(findings)
    lines = []
    lines.append(f"This assessment identified **{total} findings** across the target:\n")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    for sev in ["Critical", "High", "Medium", "Low", "Info"]:
        if counts[sev] > 0:
            lines.append(f"| {sev} | {counts[sev]} |")

    # Top 3 findings
    sorted_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    if sorted_findings:
        lines.append(f"\n### Priority Actions\n")
        for i, f in enumerate(sorted_findings[:3], 1):
            impact_summary = smart_truncate(f.get('impact', 'No impact description'), 140)
            lines.append(f"{i}. **{f.get('title', 'Untitled')}** ({f.get('severity', 'N/A')}) — {impact_summary}")

    return "\n".join(lines)


def format_finding(finding, index):
    """Format a single finding section."""
    lines = []
    fid = finding.get("id", f"VULN-{index:03d}")
    title = finding.get("title", "Untitled Finding")
    lines.append(f"### {fid} — {title}\n")
    lines.append(f"- **Severity:** {finding.get('severity', 'N/A')}")
    if finding.get("cvss"):
        lines.append(f"- **CVSS Score:** {finding['cvss']}")
    lines.append(f"- **Affected Target:** {finding.get('affected', 'N/A')}")
    lines.append(f"- **Description:** {finding.get('description', 'No description provided')}")
    lines.append(f"- **Evidence:** ```\n{finding.get('evidence', 'No evidence recorded')}\n```")
    lines.append(f"- **Impact:** {finding.get('impact', 'No impact assessment')}")
    lines.append(f"- **Remediation:** {finding.get('remediation', 'No remediation provided')}")

    if finding.get("hardening"):
        lines.append(f"- **Hardening:** {finding['hardening']}")

    if finding.get("references"):
        refs = finding["references"]
        if isinstance(refs, list):
            refs_str = ", ".join(refs)
        else:
            refs_str = str(refs)
        lines.append(f"- **References:** {refs_str}")

    return "\n".join(lines) + "\n"


def generate_report(data):
    """Generate the full report markdown."""
    target = data.get("target", "Unknown Target")
    findings = data.get("findings", [])
    enhancements = data.get("enhancements", [])
    date = datetime.now().strftime("%Y-%m-%d")

    lines = []

    # Title
    lines.append(f"# Penetration Test Report — {target}")
    lines.append(f"\n**Date:** {date}")
    lines.append(f"**Target:** {target}")
    lines.append(f"**Findings:** {len(findings)}\n")
    lines.append("---\n")

    qs = data.get("quick_scan_sections", {}) or {}
    exec_lines = clean_bullets(qs.get("executive_summary"))
    target_fp_lines = clean_bullets(qs.get("target_fingerprint"))
    why_varied_lines = clean_bullets(qs.get("why_varied"))
    next_action_lines = clean_bullets(qs.get("recommended_next_action"))
    quick_reco_lines = clean_bullets(qs.get("quick_recommendations"))

    # Executive Summary
    lines.append("## 1. Executive Summary\n")
    if exec_lines:
        for line in exec_lines:
            lines.append(f"- {line}")
        lines.append("")
    else:
        lines.append(generate_executive_summary(findings, enhancements))
    lines.append("\n---\n")

    section_no = 2
    if target_fp_lines:
        lines.append(f"## {section_no}. Target Fingerprint\n")
        for line in target_fp_lines:
            lines.append(f"- {line}")
        lines.append("\n---\n")
        section_no += 1

    if why_varied_lines:
        lines.append(f"## {section_no}. Why This Quick Scan Varied\n")
        for line in why_varied_lines:
            lines.append(f"- {line}")
        lines.append("\n---\n")
        section_no += 1

    # Methodology
    lines.append(f"## {section_no}. Methodology\n")
    if data.get("quick_scan"):
        lines.append("This assessment used the quick-scan workflow, a rapid low-impact triage process rather than a full pentest:\n")
        lines.append("1. **Reconnaissance** — Lightweight target and exposure fingerprinting")
        lines.append("2. **Enumeration** — Safe surface validation and basic discovery")
        lines.append("3. **Vulnerability Analysis** — Candidate weakness review from collected artifacts")
        lines.append("4. **Reporting** — Triage-oriented findings with next-step guidance\n")
    else:
        lines.append("The assessment followed a structured penetration testing methodology:\n")
        lines.append("1. **Reconnaissance** — Passive information gathering (DNS, WHOIS, OSINT)")
        lines.append("2. **Enumeration** — Active service discovery and fingerprinting")
        lines.append("3. **Vulnerability Analysis** — CVE matching and manual testing")
        lines.append("4. **Exploitation** — Proof-of-concept exploitation of confirmed vulnerabilities")
        lines.append("5. **Post-Exploitation** — Privilege escalation and impact assessment")
        lines.append("6. **Reporting** — Documented findings with remediation guidance\n")
    lines.append("---\n")
    section_no += 1

    # Findings
    lines.append(f"## {section_no}. Findings\n")
    sorted_findings = sorted(findings, key=lambda x: SEVERITY_ORDER.get(x.get("severity", "Info"), 99))
    for i, finding in enumerate(sorted_findings, 1):
        lines.append(format_finding(finding, i))

    lines.append("---\n")
    section_no += 1

    # Security Enhancement Recommendations
    lines.append(f"## {section_no}. Security Enhancement Recommendations\n")
    enhancement_items = list(enhancements)
    for line in quick_reco_lines:
        enhancement_items.append({"category": "Quick Scan Context", "recommendation": line})
    if enhancement_items:
        for enh in enhancement_items:
            cat = enh.get("category", "General")
            rec = enh.get("recommendation", "No recommendation provided")
            lines.append(f"### {cat}\n")
            lines.append(f"{rec}\n")
    else:
        lines.append("No additional enhancement recommendations identified.\n")
    lines.append("---\n")
    section_no += 1

    if next_action_lines:
        lines.append(f"## {section_no}. Recommended Next Action\n")
        for line in next_action_lines:
            lines.append(f"- {line}")
        lines.append("\n---\n")
        section_no += 1

    # Risk Summary Matrix
    lines.append(f"## {section_no}. Risk Summary Matrix\n")
    lines.append("| ID | Finding | Severity | Remediation Priority |")
    lines.append("|----|---------|----------|---------------------|")
    for i, f in enumerate(sorted_findings, 1):
        fid = f.get("id", f"VULN-{i:03d}")
        title = f.get("title", "Untitled")
        sev = f.get("severity", "N/A")
        priority = "Immediate" if sev in ("Critical", "High") else "Scheduled" if sev == "Medium" else "Low Priority"
        lines.append(f"| {fid} | {title} | {sev} | {priority} |")
    lines.append("")

    # Appendices
    lines.append("---\n")
    section_no += 1
    lines.append(f"## {section_no}. Appendices\n")
    lines.append("### A. Tools Used\n")
    lines.append("- nmap, masscan (enumeration)")
    lines.append("- Metasploit, custom scripts (exploitation)")
    lines.append("- Shodan, crt.sh (OSINT)")
    lines.append("- Burp Suite, curl (web testing)")
    lines.append("")
    lines.append("### B. Scope Boundaries\n")
    lines.append("All testing was conducted within the authorized scope. No denial-of-service attacks were performed without explicit permission.\n")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate pentest report from findings JSON")
    parser.add_argument("--target", required=True, help="Target name/IP for report header")
    parser.add_argument("--findings", required=True, help="Path to findings JSON file")
    parser.add_argument("--output", required=True, help="Output report path (markdown)")
    parser.add_argument("--upload-drive", action="store_true", help="Upload generated report to Google Drive via gog")
    parser.add_argument("--create-doc", action="store_true", help="Create a native Google Doc from the generated markdown")
    parser.add_argument("--export-pdf", dest="export_pdf", action="store_true", default=True,
                        help="Export the generated Google Doc to PDF for preview (default: on)")
    parser.add_argument("--no-export-pdf", dest="export_pdf", action="store_false",
                        help="Do not export a PDF preview")
    parser.add_argument("--gdrive-account", help="Google account email for gog operations")
    parser.add_argument("--gdrive-parent", help="Optional parent Drive folder ID")
    parser.add_argument("--create-slides", action="store_true", help="Create a Google Slides deck from the generated markdown")
    parser.add_argument("--slides-title", help="Slides title (default: Penetration Test Report — <target>)")
    args = parser.parse_args()

    with open(args.findings) as f:
        data = json.load(f)

    report = generate_report(data)

    with open(args.output, "w") as f:
        f.write(report)

    print(f"[OK] Report generated: {args.output}")
    print(f"     Target: {args.target}")
    print(f"     Findings: {len(data.get('findings', []))}")
    print(f"     Enhancements: {len(data.get('enhancements', []))}")

    publish_summary = {
        "local_file": args.output,
        "drive_link": None,
        "doc_link": None,
        "slides_link": None,
        "pdf_link": None,
        "drive_id": None,
        "doc_id": None,
        "slides_id": None,
        "pdf_id": None,
    }

    if args.upload_drive:
        try:
            upload_result = upload_to_drive(args.output, account=args.gdrive_account, parent=args.gdrive_parent)
            file_data = upload_result.get("file", upload_result) if isinstance(upload_result, dict) else upload_result
            if isinstance(file_data, dict):
                publish_summary["drive_id"] = file_data.get("id")
                publish_summary["drive_link"] = file_data.get("webViewLink")
                print(f"[OK] Drive upload: {file_data.get('name', args.output)}")
                if file_data.get("id"):
                    print(f"     Drive File ID: {file_data['id']}")
                if file_data.get("webViewLink"):
                    print(f"     Drive Link: {file_data['webViewLink']}")
            else:
                print(f"[OK] Drive upload completed: {file_data}")
        except Exception as e:
            print(f"[WARN] Drive upload failed: {e}")

    if args.create_doc:
        try:
            docx_path = Path(args.output).with_suffix(".docx")
            build_docx(data, str(docx_path))
            print(f"[OK] DocX generated: {docx_path}")
            doc_result = upload_to_drive(str(docx_path), account=args.gdrive_account, parent=args.gdrive_parent, convert_to="doc")
            doc_data = doc_result.get("file", doc_result) if isinstance(doc_result, dict) else doc_result
            if isinstance(doc_data, dict):
                publish_summary["doc_id"] = doc_data.get("id")
                publish_summary["doc_link"] = doc_data.get("webViewLink")
                print(f"[OK] Google Doc created: {doc_data.get('name', args.output)}")
                if doc_data.get("id"):
                    print(f"     Doc ID: {doc_data['id']}")
                if doc_data.get("webViewLink"):
                    print(f"     Doc Link: {doc_data['webViewLink']}")
            else:
                print(f"[OK] Google Doc created: {doc_data}")
        except Exception as e:
            print(f"[WARN] Google Doc creation failed: {e}")

    if args.create_doc and args.export_pdf and publish_summary.get("doc_id"):
        try:
            pdf_path = export_doc_to_pdf(publish_summary["doc_id"], account=args.gdrive_account)
            pdf_result = upload_to_drive(str(pdf_path), account=args.gdrive_account, parent=args.gdrive_parent)
            pdf_data = pdf_result.get("file", pdf_result) if isinstance(pdf_result, dict) else pdf_result
            if isinstance(pdf_data, dict):
                publish_summary["pdf_id"] = pdf_data.get("id")
                publish_summary["pdf_link"] = pdf_data.get("webViewLink")
                print(f"[OK] PDF preview uploaded: {pdf_data.get('name', pdf_path)}")
                if pdf_data.get("webViewLink"):
                    print(f"     PDF Link: {pdf_data['webViewLink']}")
            else:
                print(f"[OK] PDF preview uploaded: {pdf_data}")
            if pdf_path.exists():
                pdf_path.unlink()
        except Exception as e:
            print(f"[WARN] PDF export/upload failed: {e}")

    if args.create_slides:
        slides_title = args.slides_title or f"Penetration Test Report — {args.target}"
        try:
            pptx_output = str(Path(args.output).with_suffix(".pptx"))
            build_styled_pptx(data, pptx_output, title=slides_title)
            print(f"[OK] Styled PPTX generated: {pptx_output}")
            slides_result = upload_pptx_as_slides(pptx_output, account=args.gdrive_account, parent=args.gdrive_parent, name=slides_title)
            pres = slides_result.get("file", slides_result) if isinstance(slides_result, dict) else slides_result
            if isinstance(pres, dict):
                publish_summary["slides_id"] = pres.get("presentationId") or pres.get("id")
                publish_summary["slides_link"] = pres.get("webViewLink")
                if not publish_summary["slides_link"] and publish_summary["slides_id"]:
                    publish_summary["slides_link"] = f"https://docs.google.com/presentation/d/{publish_summary['slides_id']}/edit?usp=drivesdk"
                print(f"[OK] Styled Slides created: {pres.get('name', slides_title)}")
                if publish_summary["slides_id"]:
                    print(f"     Slides ID: {publish_summary['slides_id']}")
                if publish_summary["slides_link"]:
                    print(f"     Slides Link: {publish_summary['slides_link']}")
            else:
                print(f"[OK] Styled Slides created: {slides_result}")
        except Exception as e:
            print(f"[WARN] Slides creation failed: {e}")

    if any(publish_summary[k] for k in ("drive_link", "doc_link", "slides_link")):
        print("\n=== PUBLISHED LINKS ===")
        print(f"Local file: {publish_summary['local_file']}")
        if publish_summary["doc_link"]:
            print(f"Docs: {publish_summary['doc_link']}")
        if publish_summary["pdf_link"]:
            print(f"PDF preview: {publish_summary['pdf_link']}")
        if publish_summary["slides_link"]:
            print(f"Slides: {publish_summary['slides_link']}")
        if publish_summary["drive_link"]:
            print(f"Drive file: {publish_summary['drive_link']}")


if __name__ == "__main__":
    main()
